# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 10

# Number of days of inactivity before a stale Issue or Pull Request is closed
daysUntilClose: 10

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This project is not maintained anymore and was replaced. Please see https://github.com/sequelpro/sequelpro/issues/3705.

# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false

# Comment to post when closing a stale Issue or Pull Request. Set to `false` to disable
closeComment: >
  This issue has been auto-closed.
  If you are still experiencing a problem, please open a new issue in new project. For more info, check https://github.com/sequelpro/sequelpro/issues/3705

# Limit to only `issues`
only: issues
